apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloner
  template:
    metadata:
      labels:
        app: cloner
    spec:
      containers:
      - name: folio
        image: simranbanwait/portfolio
        ports:
        - containerPort: 80
